### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by CompuIves** [pimterry/lambda-git#5]
Wanted to leave a big thanks here, this saved me hours of research and work for getting git to work in lambda. Thanks again! ❤️

**Comment by pimterry** [comment]
No worries at all, most of the credit should really go to @mhart, since this is just bundling his git build from https://github.com/lambci/lambci/tree/master/vendor. Glad it's useful though!

**Comment by mhart** [comment]
@pimterry oh cool, glad you're making use of this – would be nice to have an explanation of the source on the README!

**Comment by pimterry** [comment]
@mhart good point, done: https://github.com/pimterry/lambda-git/commit/3a43a50d5f569a7252faa846e32f7a9e0a352b24
