### ISSUE TITLE
Clearer sample code

### ISSUE THREAD

**Issue by marcelobern** [pimterry/lambda-git#9]
It took me a few hours and checking into the code to figure out how to actually make this work.

I suggest updating the `README.md` sample to something like:

```
require("lambda-git")()
	.then(function (env) {
		// git is ready for you!!!
		console.log("env was setup: " + JSON.stringify(env));
	})
	.catch(function (error) {
		// do your error treatment here, git is likely not loaded
	});
```

Thanks!

**Comment by pimterry** [comment]
Thanks for the feedback @marcelobern! Good idea, done.
